### ISSUE TITLE
pcodedmp can't be installed in either Ubuntu and Windows 10

### ISSUE THREAD

**Issue by pcodetry** [bontchev/pcodedmp#16]
in Windows 10, I use python 27 for setup.py, I encounter error:
warning: pypandoc module not found, could not convert Markdown to RST
Traceback (most recent call last):
  File "f:\pcode\setup.py", line 100, in <module>
    long_description=read_md('README.md'),
  File "f:\pcode\setup.py", line 21, in read_md
    def read_md(f): return open(f, 'r').read()
IOError: [Errno 2] No such file or directory: 'README.md', in linux, same error i use pip install .  pls see attachment
[install_error.docx](https://github.com/bontchev/pcodedmp/files/5225005/install_error.docx)
, I unzip your files

**Comment by bontchev** [comment]
I do not use Windows 10 but I am using `pcodedmp` on both Windows 7 and Ubuntu Linux 16.04 just fine.

Try installing the missing module separately? Use the command

```bash
pip install pypandoc
```

(This is not a module that `pcodedmp` uses; it is used only by the setup process.)

How are you trying to install `pcodedmp`? Via `pip` or manually from a cloned repository?

**Comment by bontchev** [comment]
Since you've commented on what the program can and cannot do in a different issue, I assume that you have managed to install it successfully, so I am closing this issue now. If I am wrong and there are indeed some installation problems, please explain them clearly and I'll re-open the issue.
