### ISSUE TITLE
Website installation instructions are incomplete

### ISSUE THREAD

**Issue by GadgetSteve** [bontchev/pcodedmp#5]
The Installation section of the current web site mentions installing the pre-requisite oletools but does not mention actually installing pcodedmp this could lead to inexperienced _or even experienced but time challenged_ users failing to install it.

Please consider adding pcodedmp to the two pip lines given or having a separate line of: `pip install -U pcodedmp`

**Comment by bontchev** [comment]
I'm not sure I understand the problem... If you install `pcodedmp` with `pip`, it _will_ install the right version of `oletools`. The instructions in the "Installation" section are for manually downloading the script from GitHub and using it; they were written before `pcodedmp` was installable with `pip`.

**Comment by GadgetSteve** [comment]
The problem is that if the users follow the installation section instructions literally they will install oletools instead of  pcodedmp not with it.

**Comment by bontchev** [comment]
But if they install `oletools` (as described in the Installation section), they don't need to install `pcodedmp` - it can simply be downloaded from the repository and will run anywhere. I ended up making `pcodedmp` installable via `pip` mostly to save the user the trouble to install any dependencies first (of which there currently is only one - `oletools` - but this could change in the future and I was trying to make things simpler for the user...

Do you want me to just add at the end of the Installation section something like

> Alternatively, you can install `pcodedmp` directly with `pip` by using the command
> `pip install -U pcodedmp`
> and it will take care of installing all the necessary dependencies (like `oletools`).

**Comment by GadgetSteve** [comment]
Sounds good. My concern was that someone, (like myself), could follow the install instructions: pip install oletools and then type pcodedmp and receive an error message as despite following all of the current instructions in the installation section I have not yet installed pcodedmp. This actually happened to me.

**Comment by bontchev** [comment]
OK, done. Closing the issue now.
